'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Items', [{
      id: 1,
      number: '9091',
      uom: 'uom1',
      brand: 'SONY',
      defaultCost: 10,
      discountable: true,
      isProduct: true,
      effectiveDate: new Date(),
      finalSale: true,
      cartonHeight: 5.0,
      cartonWeight: 5.0,
      inventoried: false,
      description: 'A nice golden ring',
      name: 'Golden Ring',
      weight: 8.0,
      makeBuy: true,
      minimumOrderQty: 1,
      obsolete: false,
      originCountry: 'USA',
      shipable: false,
      volume: 7.1,
      webActive: true,
      webActiveDescription: 'Buy this golden ring',
      zeroPrice: false,
      active: true,
      retailPrice: 455.99,
      salesPrice: 122.99,
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      id: 2,
      number: '9091',
      uom: 'uom2',
      brand: 'SAMSUNG',
      defaultCost: 10,
      discountable: true,
      isProduct: true,
      effectiveDate: new Date(),
      finalSale: true,
      cartonHeight: 2.0,
      cartonWeight: 5.0,
      inventoried: true,
      description: 'A nice silver ring',
      name: 'Silver Ring',
      weight: 3.0,
      makeBuy: true,
      minimumOrderQty: 4,
      obsolete: false,
      originCountry: 'ES',
      shipable: true,
      volume: 7.1,
      webActive: true,
      webActiveDescription: 'Buy this silver ring',
      zeroPrice: false,
      active: true,
      retailPrice: 710.99,
      salesPrice: 165.99,
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      id: 3,
      number: '9093',
      uom: 'uom3',
      brand: 'PANASONIC',
      defaultCost: 7,
      discountable: false,
      isProduct: true,
      effectiveDate: new Date(),
      finalSale: false,
      cartonHeight: 5.0,
      cartonWeight: 3.0,
      inventoried: false,
      description: 'A nice golden chain',
      name: 'Golden Chain',
      weight: 6.0,
      makeBuy: true,
      minimumOrderQty: 3,
      obsolete: false,
      originCountry: 'CU',
      shipable: true,
      volume: 4.1,
      webActive: true,
      webActiveDescription: 'Buy this golden chain',
      zeroPrice: false,
      active: true,
      retailPrice: 110.99,
      salesPrice: 145.99,
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      id: 4,
      number: '9094',
      uom: 'uom4',
      brand: 'SONY',
      defaultCost: 10,
      discountable: true,
      isProduct: true,
      effectiveDate: new Date(),
      finalSale: true,
      cartonHeight: 5.0,
      cartonWeight: 5.0,
      inventoried: false,
      description: 'A nice earing',
      name: 'Golden earing',
      weight: 8.0,
      makeBuy: true,
      minimumOrderQty: 1,
      obsolete: false,
      originCountry: 'USA',
      shipable: false,
      volume: 7.1,
      webActive: true,
      webActiveDescription: 'Buy this golden earing',
      zeroPrice: false,
      active: true,
      retailPrice: 140.99,
      salesPrice: 151.99,
      createdAt: new Date(),
      updatedAt: new Date()
    }]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Items', null, {});
  }
};
